export type MajorAssessmentQuestion = { question: string; options: string[]; answer: number; explanation: string };

const q = (question: string, options: string[], answer: number, explanation: string): MajorAssessmentQuestion => ({ question, options, answer, explanation });

export const quiz3Questions: MajorAssessmentQuestion[] = [
  q('Which statement is evidence rather than an assumption?', ['Three of five interviewees said they could not find the help link.','Customers are probably frustrated by the new process.','AI predicts that satisfaction will increase.','The manager believes the issue is minor.'], 0, 'A direct report from identified research is evidence; the other statements are assumptions, predictions, or opinions.'),
  q('Why should a customer insight name its source?', ['So the insight sounds more formal.','So a manager can trace and evaluate the evidence behind it.','So AI can make the final decision.','So every source receives the same weight.'], 1, 'Traceability lets the manager inspect whether the evidence actually supports the insight.'),
  q('What is a missing customer voice?', ['A customer who agrees with the manager.','An AI-generated persona.','A customer whose relevant perspective is not represented in the evidence.','A customer who used the service recently.'], 2, 'A missing voice is a relevant perspective that the current evidence does not adequately represent.'),
  q('AI summarizes feedback and says, “Customers want weekend hours.” What should happen next?', ['Treat the statement as observed evidence.','Publish it because the wording is clear.','Ask AI to make the statement more confident.','Trace the claim to the underlying feedback and label it appropriately.'], 3, 'The manager must determine whether the claim is supported and whether it is observation, inference, or AI-generated interpretation.'),
  q('What should a decision brief do before recommending action?', ['Compare realistic options, tradeoffs, evidence, and remaining uncertainty.','Hide uncertainty to make the decision easier.','Choose the most automated option.','Use only the manager’s preferred source.'], 0, 'A decision brief should make evidence, tradeoffs, and uncertainty visible before the recommendation.'),
  q('Which workflow has meaningful human review?', ['AI drafts and automatically publishes.','AI drafts; a person verifies evidence, can revise or stop the output, and then approves.','AI drafts and a person clicks approve without seeing the source.','AI drafts and another AI approves.'], 1, 'Meaningful review requires relevant evidence plus authority to change, reject, or escalate the output.'),
  q('What is the purpose of an escalation trigger?', ['To make every case take longer.','To let AI choose the accountable owner.','To identify conditions that require the normal workflow to stop and receive additional review.','To remove documentation requirements.'], 2, 'Escalation triggers define when a case is too uncertain, risky, or consequential for the normal workflow.'),
  q('AI calculates a 24% increase in complaints. What should the reviewer verify?', ['Only whether 24% looks reasonable.','Only the AI tool name.','Nothing if the number is precise.','The source counts, time periods, calculation, and context.'], 3, 'Precise numbers still require source and calculation checks.'),
  q('What is the strongest connection between Week 8 and Week 9?', ['Week 9 turns a documented Week 8 problem into a controlled AI-assisted workflow.','Week 9 starts a completely unrelated project.','Week 9 replaces the evidence gathered in Week 8.','Week 9 removes the manager from the decision.'], 0, 'The workflow should be grounded in the customer problem and evidence already documented in Week 8.'),
  q('Who should own the final decision in a human-reviewed AI workflow?', ['The AI model.','A named accountable human role.','The software vendor.','Whichever employee used the tool first.'], 1, 'The workflow should identify a human role with authority and responsibility for the final decision.'),
  q('A reviewer cannot confirm an important source used by an AI output. What is the best action?', ['Use the claim but add a warning.','Replace the source with another AI answer.','Mark the claim unresolved and do not rely on it until it is verified.','Remove the source note.'], 2, 'Unresolved evidence should not quietly become the basis for a consequential decision.'),
  q('What test evidence is most useful for the Week 9 workflow?', ['A screenshot of the empty form.','A list of AI buzzwords.','A statement that the workflow probably works.','One fictional or permitted case showing input, AI-supported output, human review, changes, and final result.'], 3, 'A concrete end-to-end test demonstrates how the controls behave in practice.')
];

export const test2Questions: MajorAssessmentQuestion[] = [
  q('When does AI assistance become substitution?', ['When AI replaces meaningful student or manager thinking that the person is expected to perform and present as their own.','When AI helps brainstorm.','When AI checks grammar.','When a person reviews a draft.'], 0, 'Substitution occurs when AI replaces the human contribution or judgment the task is meant to assess.'),
  q('What makes an AI disclosure strong?', ['It says only “AI was used.”','It explains the tool, task, AI contribution, human changes, verification, and final responsibility.','It lists the model name only.','It avoids mentioning verification.'], 1, 'A useful disclosure makes the division of work and human responsibility visible.'),
  q('Why is attribution different from simply naming an AI tool?', ['Attribution guarantees the content is correct.','Attribution eliminates the need for sources.','Attribution traces where information or contributions came from and gives appropriate credit.','Attribution is only about formatting.'], 2, 'Attribution is about origin and credit, not just naming software.'),
  q('What is a verification record?', ['A copy of every prompt ever written.','A list of AI tools.','A statement that the output looked correct.','A note showing what output or claim was checked, how it was checked, what was found, and who reviewed it.'], 3, 'Verification records document the evidence and human review behind an AI-assisted result.'),
  q('Accountable authorship means:', ['The person submitting or approving the work understands, verifies, edits, and takes responsibility for it.','The AI owns mistakes in the final report.','No disclosure is needed if AI helped.','Only original typing counts as authorship.'], 0, 'Human ownership remains necessary even when AI contributes substantially.'),
  q('Why is human dignity relevant to AI-enabled management?', ['Dignity means AI cannot be used at work.','People should not be reduced to scores or outputs when decisions affect them.','Dignity requires identical decisions in every case.','Dignity is only a technical issue.'], 1, 'Managers should treat affected people as persons with worth, context, and appropriate opportunities for review or remedy.'),
  q('An unverified statistic appears in a leadership presentation. Which value is most directly at stake?', ['Speed.','Automation.','Truthfulness.','Branding.'], 2, 'Truthfulness requires honest, supportable communication rather than presenting unsupported claims as fact.'),
  q('Historical data causes one group to receive lower promotion scores. What should a manager do?', ['Assume the data is objective.','Automatically accept the ranking.','Hide group-level results.','Investigate whether the criteria, history, and outcomes create unfair disadvantage before using the scores.'], 3, 'Justice and fairness require examining how data and criteria affect people, not assuming technical output is neutral.'),
  q('What does stewardship add to an AI decision?', ['Responsible use of people, information, authority, and resources with attention to long-term consequences.','A focus only on short-term cost savings.','A requirement to automate every efficient task.','A rule that managers cannot experiment.'], 0, 'Stewardship considers how entrusted resources and authority are used over time.'),
  q('What is moral discernment?', ['Automatically following the most efficient recommendation.','Using judgment to weigh evidence, values, consequences, and responsibilities before deciding.','Letting AI choose the value that matters most.','Avoiding difficult decisions.'], 1, 'Discernment requires thoughtful human judgment when important values or outcomes are in tension.'),
  q('What is the difference between a task and a job?', ['A task and job are always identical.','A task is always automated.','A job is made up of multiple tasks and responsibilities.','A job is only a job title.'], 2, 'AI often changes individual tasks without eliminating the whole job.'),
  q('Which example is augmentation?', ['AI automatically fires an employee.','AI replaces every task in a role.','AI hides the original evidence.','AI drafts a customer-response summary and an employee uses it while handling the case.'], 3, 'Augmentation means AI assists human work while the person remains actively responsible.'),
  q('Which work is most likely to remain primarily human?', ['A high-stakes conversation requiring empathy, context, judgment, and accountability.','Reformatting a standard table.','Sorting a non-sensitive list alphabetically.','Drafting a first-pass agenda.'], 0, 'High-context, relational, consequential work often requires meaningful human judgment.'),
  q('Why should worker voice be included in AI implementation?', ['Worker input guarantees everyone will agree.','Workers can identify practical effects, hidden risks, and workflow problems that leaders may not see.','Worker voice replaces management accountability.','Worker voice is only needed after failure.'], 1, 'Affected workers often hold important operational evidence about how a change actually functions.'),
  q('What is reskilling?', ['Replacing employees without training.','Buying a new AI model.','Preparing workers with new capabilities as tasks and responsibilities change.','Removing human review.'], 2, 'Reskilling supports workers as technology changes the skills required for their work.'),
  q('What is transition risk?', ['The certainty that AI will fail.','The cost of a single software license.','The risk that a prompt is too short.','The possibility of disruption or harm while moving to a new AI-enabled way of working.'], 3, 'Transition risk concerns the change process, including readiness, training, ownership, and operational continuity.'),
  q('Employees receive little training before an AI tool changes their responsibilities. What is the strongest response?', ['Add training, a pilot, clear roles, feedback channels, monitoring, and a fallback process before scaling.','Launch anyway and learn later.','Make AI decisions final.','Remove the old process immediately.'], 0, 'Responsible transition planning builds readiness and preserves a safe recovery path.'),
  q('What should a Workforce Impact Map distinguish?', ['Only jobs that can be eliminated.','Automation, augmentation, and work that should remain human.','Only employee preferences.','Only software features.'], 1, 'The map should show how tasks change and where human judgment remains essential.'),
  q('A company can save money by automating an employee-facing process, but the tool sometimes gives incomplete policy guidance. What should the manager prioritize?', ['Cost savings alone.','The newest model.','Safeguards, human escalation, accuracy testing, affected people, and consequences of wrong guidance.','Automatic expansion.'], 2, 'Efficiency is one consideration, not a substitute for risk, dignity, truthfulness, and accountable service.'),
  q('Which statement best connects Weeks 10–12?', ['Each week is unrelated.','All three weeks recommend replacing human judgment.','Only technical accuracy matters.','Transparency about AI use, values-based judgment, and workforce responsibility all preserve human accountability.'], 3, 'The three weeks connect responsible authorship, ethical judgment, and responsibility to people affected by AI-enabled work.'),
  q('A manager cannot explain why an AI system recommended an employee for discipline. What should happen?', ['Pause consequential action until the evidence, rationale, policy, and human review are adequate.','Use the recommendation because the model is complex.','Ask the AI to write a more confident explanation.','Remove the employee’s opportunity to respond.'], 0, 'High-stakes action requires evidence, review, accountability, and a defensible process.'),
  q('Which disclosure best preserves accountable authorship?', ['“AI did this.”','“I used AI to organize the first draft; I verified the cited figures, rewrote the recommendation, and I am responsible for the final submission.”','“Some tools may have been used.”','No disclosure because the final document was edited.'], 1, 'The disclosure identifies contribution, verification, human changes, and ownership.'),
  q('What should happen when an AI recommendation conflicts with important values or evidence?', ['Follow the AI because it is faster.','Delete the evidence.','Investigate further, weigh the conflict, apply safeguards, and make an accountable human decision.','Ask the vendor to own the decision.'], 2, 'Managers should not outsource value conflicts or evidence judgments to the system.'),
  q('What is a worker-centered safeguard during AI-driven change?', ['Immediate role elimination.','No communication until launch.','Automatic disciplinary use of AI scores.','A feedback and appeal path, training, clear role expectations, and monitoring for harmful effects.'], 3, 'Worker-centered safeguards give affected people support, information, voice, and remedy.'),
  q('Who remains accountable for an AI-assisted workplace decision?', ['The responsible people and organization using the system.','The AI alone.','Nobody if the model is accurate.','Only the vendor.'], 0, 'AI support does not transfer accountability away from the organization and its decision-makers.')
];

export const quiz4Questions: MajorAssessmentQuestion[] = [
  q('What makes an AI implementation problem well framed?', ['It starts with a tool and searches for any possible use.','It names a business problem, intended users, boundaries, and the outcome to improve.','It assumes every task should use AI.','It avoids defining success.'], 1, 'Implementation should start with a real problem and bounded purpose rather than technology for its own sake.'),
  q('Why should expected benefits have a baseline?', ['So AI can choose the KPI.','So the pilot cannot be stopped.','So improvement can be measured against the current state.','So only positive results are recorded.'], 2, 'A baseline makes it possible to tell whether the change actually improved performance.'),
  q('What is a stop condition?', ['A deadline for writing the prompt.','A rule that pilots must always continue.','A marketing goal.','A specific result or risk threshold that triggers pause, review, or termination of the pilot.'], 3, 'Stop conditions prevent teams from continuing a harmful or ineffective implementation by default.'),
  q('Which rollout is most responsible?', ['A bounded pilot with owners, training, controls, monitoring, review points, and stop conditions.','Immediate organization-wide deployment.','A launch with no baseline.','A launch in which the vendor owns all decisions.'], 0, 'A bounded pilot lets managers gather evidence while limiting exposure and preserving control.'),
  q('What is an acceptance criterion?', ['A general feeling that the dashboard looks good.','A clear condition the dashboard must meet to be considered ready.','A list of future ideas.','A requirement that there be no limitations.'], 1, 'Acceptance criteria translate readiness into specific, testable expectations.'),
  q('Why test the dashboard as a first-time user?', ['To avoid testing content.','To prove no revision is needed.','To reveal navigation, instruction, and usability problems that the builder may no longer notice.','To replace peer feedback.'], 2, 'Fresh-user testing exposes assumptions and friction hidden by familiarity.'),
  q('A peer tester finds an unsupported claim. What priority should it receive?', ['Low because the interface still works.','None if AI wrote it.','Low if the text is polished.','High if the claim could affect a management decision or trust in the dashboard.'], 3, 'Evidence and trust problems can be high-impact even when the interface technically works.'),
  q('What is the purpose of retesting after a revision?', ['To verify the fix works and did not create a new problem.','To avoid documenting defects.','To make the change look complete.','To remove peer feedback.'], 0, 'A revision is not verified until the affected flow is tested again.'),
  q('Which release decision is strongest when a high-priority defect remains unresolved?', ['Release without mentioning it.','Revise and retest or do not release, depending on the defect’s impact.','Delete the test record.','Ask AI to downgrade the defect.'], 1, 'Release readiness should follow evidence and risk, not schedule pressure.'),
  q('A future AI capability looks impressive but lacks evidence about its effect on employees. What should the manager do?', ['Deploy immediately to stay competitive.','Assume vendor claims are sufficient.','Treat it as a proposal, identify risks and needed evidence, and use a bounded pilot only if safeguards are adequate.','Remove human review.'], 2, 'Emerging capability should be evaluated with the same evidence, risk, and accountability standards as current tools.'),
  q('What best connects Week 13 and Week 14?', ['The weeks are separate projects.','Week 14 replaces all Week 13 planning.','Week 13 eliminates the need for testing.','Week 13 plans responsible implementation; Week 14 tests whether the dashboard and controls are actually ready.'], 3, 'Implementation planning and release testing are complementary parts of responsible deployment.'),
  q('Who should make the final release-readiness decision?', ['A named accountable human role using test evidence, risk, limitations, and policy requirements.','The AI system.','The newest team member.','The vendor automatically.'], 0, 'Release is a management decision supported by evidence, not an automated default.')
];
