from pathlib import Path

PAGE = Path('ai-for-managers-dashboard/app/page.tsx')
text = PAGE.read_text()


def replace_once(old: str, new: str, label: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected exactly one match, found {count}')
    text = text.replace(old, new, 1)

# 1) Keep specialized lesson data scoped to the weeks that own it.
replace_once(
    "    const lessonData = selectedWeek === 6 ? ethicsLessons[lessonIndex] : governanceLessons[lessonIndex];",
    "    const lessonData = selectedWeek === 6 ? ethicsLessons[lessonIndex] : selectedWeek === 7 ? governanceLessons[lessonIndex] : null;",
    'scope lessonData to Weeks 6 and 7',
)

# 2) Scope Lena's Week 10 Academic Integrity lesson to Week 10 Lesson 1 only.
old_lesson = '''        <section className="lmsPanel structuredLesson"><div className="panelBar"><h3>Know · Understand · Apply</h3><span>Lesson {lessonIndex + 1}</span></div><div className="knowGrid"><article><strong>KNOW</strong><p>Key vocabulary: Academic Integrity, Plagiarism, Original Work, Attribution, and AI Disclosure.<br /><br />Academic integrity means completing work honestly, responsibly, and transparently. When using AI, students are still responsible for ensuring that submitted work reflects their own thinking and follows course expectations.</p></article><article><strong>UNDERSTAND</strong><p><strong>Concept:</strong> Using AI does not automatically violate academic integrity. The concern is <strong>how AI is used and represented</strong>.<br /><br /><strong>Student example:</strong> A student writes an assignment independently and uses AI to check grammar. Another student asks AI to write the entire assignment and submits it as their own.<br /><br /><strong>Student decision:</strong> Are both students using AI appropriately?<br /><br /><strong>Feedback:</strong> No. AI can support a student&apos;s work, but it should not replace the student&apos;s thinking or contribution. Significant AI assistance should also be disclosed when required.<br /><br /><strong>Manager takeaway:</strong> The same principle applies in the workplace. Managers are responsible for being transparent about AI use, verifying AI-generated information, and taking responsibility for the final work.</p></article><article><strong>APPLY</strong><p><strong>Decision prompt:</strong> A student uses AI to generate two paragraphs of an assignment, changes several words, and submits the work without disclosing the AI use. Does this demonstrate academic integrity? Explain why or why not and describe what the student should have done differently.<br /><br /><strong>Expected answer:</strong> No. This does not demonstrate academic integrity because the student relied on AI to generate substantial content, revised only a few words, and submitted the work without disclosure. The student should have disclosed the AI assistance if the assignment required it, significantly revised the AI-generated content, and made sure the final work reflects their own thinking, analysis, and writing.</p></article></div></section>'''
new_lesson = '''        {selectedWeek === 10 && lessonIndex === 0 ? <section className="lmsPanel structuredLesson"><div className="panelBar"><h3>Know · Understand · Apply</h3><span>Lesson {lessonIndex + 1}</span></div><div className="knowGrid"><article><strong>KNOW</strong><p>Key vocabulary: Academic Integrity, Plagiarism, Original Work, Attribution, and AI Disclosure.<br /><br />Academic integrity means completing work honestly, responsibly, and transparently. When using AI, students are still responsible for ensuring that submitted work reflects their own thinking and follows course expectations.</p></article><article><strong>UNDERSTAND</strong><p><strong>Concept:</strong> Using AI does not automatically violate academic integrity. The concern is <strong>how AI is used and represented</strong>.<br /><br /><strong>Student example:</strong> A student writes an assignment independently and uses AI to check grammar. Another student asks AI to write the entire assignment and submits it as their own.<br /><br /><strong>Student decision:</strong> Are both students using AI appropriately?<br /><br /><strong>Feedback:</strong> No. AI can support a student&apos;s work, but it should not replace the student&apos;s thinking or contribution. Significant AI assistance should also be disclosed when required.<br /><br /><strong>Manager takeaway:</strong> The same principle applies in the workplace. Managers are responsible for being transparent about AI use, verifying AI-generated information, and taking responsibility for the final work.</p></article><article><strong>APPLY</strong><p><strong>Decision prompt:</strong> A student uses AI to generate two paragraphs of an assignment, changes several words, and submits the work without disclosing the AI use. Does this demonstrate academic integrity? Explain why or why not and describe what the student should have done differently.<br /><br /><strong>Expected answer:</strong> No. This does not demonstrate academic integrity because the student relied on AI to generate substantial content, revised only a few words, and submitted the work without disclosure. The student should have disclosed the AI assistance if the assignment required it, significantly revised the AI-generated content, and made sure the final work reflects their own thinking, analysis, and writing.</p></article></div></section> : <section className="lmsPanel structuredLesson"><div className="panelBar"><h3>Know · Understand · Apply</h3><span>Lesson {lessonIndex + 1}</span></div><div className="knowGrid"><article><strong>KNOW</strong><p>Key vocabulary: {selectedItem.title.replace(/^Lesson \\d+ · /, '')} and its relationship to responsible management.</p></article><article><strong>UNDERSTAND</strong><p>{lessonData?.[1] || selectedItem.description}</p></article><article><strong>APPLY</strong><p>{lessonData?.[2] || 'Name the owner, affected stakeholders, evidence, and safeguard for a realistic management use case.'}</p></article></div></section>}'''
replace_once(old_lesson, new_lesson, 'scope Week 10 lesson content')

# 3) Reconcile roadmap copy with the actual structured modules.
old_week8 = "  { week: 8, dates: 'Oct 12–18', title: 'AI in Management', learn: 'Customer research, journey mapping, segmentation, privacy, and synthetic-data limits.', build: 'Add a customer-insight board using de-identified or synthetic inputs.', test: 'Look for invented needs, weak segments, missing voices, and privacy risks.', manage: 'Define which customer conclusions require human research before action.', present: 'Share one evidence-based customer insight and one unresolved question.', output: 'Manager AI Assistant + decision brief', studentQuestion: 'How can AI help a manager without replacing human judgment?', studentWin: 'Use AI to organize customer evidence without treating synthetic patterns as facts.', career: 'Support marketing, service design, and customer-experience decisions.', workload: '7–9 hours' },"
new_week8 = "  { week: 8, dates: 'Oct 12–18', title: 'AI in Management', learn: 'AI in leadership and communication, planning, project management, agents, decision support, and human-in-the-loop judgment.', build: 'Add a Manager AI Assistant that prepares a decision brief with context, options, tradeoffs, risks, and a clearly labeled human decision.', test: 'Challenge assumptions, missing information, unsupported recommendations, and places where human review is required.', manage: 'Keep decision rights with the manager and define when AI output must be verified, revised, or escalated.', present: 'Compare the AI recommendation with your own management decision and identify the evidence still needed.', output: 'Manager AI Assistant + decision brief', studentQuestion: 'How can AI help a manager without replacing human judgment?', studentWin: 'Use AI to frame and compare management options while keeping the final decision human.', career: 'Use AI as decision support without surrendering accountability.', workload: '7–9 hours' },"
replace_once(old_week8, new_week8, 'align Week 8 roadmap')

old_week9 = "  { week: 9, dates: 'Oct 19–25', title: 'Accuracy, Hallucinations, and Verification', learn: 'AI in hiring, coaching, performance, collaboration, and employee decision-making.', build: 'Add a team-support workflow with explicit human review and fairness checks.', test: 'Probe bias, inappropriate inference, privacy, and high-stakes decision boundaries.', manage: 'Separate administrative assistance from decisions about people.', present: 'Defend where AI may assist and where it must not decide.', output: 'AI Verification Center + Quiz 3', studentQuestion: 'How can a manager verify AI output before acting on it?', studentWin: 'Design a people workflow that improves support without automating human judgment.', career: 'Manage teams and HR-related processes more responsibly.', workload: '7–9 hours' },"
new_week9 = "  { week: 9, dates: 'Oct 19–25', title: 'Accuracy, Hallucinations, and Verification', learn: 'Hallucinations, source quality, claim verification, calculation checks, uncertainty, and correction workflows.', build: 'Add an AI Verification Center that records the claim, source, verification method, result, correction, and confidence level.', test: 'Audit AI-generated claims for source quality, math, unsupported causal language, stale information, and unresolved uncertainty.', manage: 'Require evidence before acting on consequential AI output and document corrections when the output is wrong.', present: 'Show what was confirmed, corrected, or left unresolved and explain why.', output: 'AI Verification Center + Quiz 3', studentQuestion: 'How can a manager verify AI output before acting on it?', studentWin: 'Turn verification into a repeatable management checkpoint instead of trusting fluent output.', career: 'Verify AI-assisted work before it informs business decisions.', workload: '7–9 hours' },"
replace_once(old_week9, new_week9, 'align Week 9 roadmap')

old_week11 = "  { week: 11, dates: 'Nov 2–8', title: 'Christian Perspective on AI', learn: 'Competitive analysis, strategic options, assumptions, and second-order effects.', build: 'Add a strategy canvas comparing three plausible choices.', test: 'Challenge source quality, hidden assumptions, and missing alternatives.', manage: 'Clarify who recommends, who decides, and who monitors results.', present: 'Defend one strategic option and explain why the others were rejected.', output: 'Strategy canvas + decision memo', studentQuestion: 'Can AI help with strategy without choosing for me?', studentWin: 'Use AI to widen strategic options while retaining managerial accountability.', career: 'Prepare structured options for executive decision-making.', workload: '7–9 hours' },"
new_week11 = "  { week: 11, dates: 'Nov 2–8', title: 'Christian Perspective on AI', learn: 'Human dignity, truthfulness, justice and fairness, stewardship, responsibility, and moral discernment in AI-assisted decisions.', build: 'Add a Values-Based AI Decision Framework recording the situation, affected people, values, tensions, evidence, safeguards, and accountable decision.', test: 'Challenge whether the recommendation respects people, tells the truth about uncertainty, distributes benefits and burdens fairly, and preserves accountability.', manage: 'Use values to evaluate tradeoffs without reducing ethical judgment to slogans.', present: 'Defend a values-based recommendation and explain the tensions and safeguards involved.', output: 'Values-Based AI Decision Framework + decision memo', studentQuestion: 'What should guide a manager when an efficient AI choice conflicts with important values?', studentWin: 'Use a structured values framework to make a defensible AI management decision.', career: 'Bring ethical reasoning and accountability into technology-enabled decisions.', workload: '7–9 hours' },"
replace_once(old_week11, new_week11, 'align Week 11 roadmap')

old_week12 = "  { week: 12, dates: 'Nov 9–15', title: 'AI and the Workforce', learn: 'Opportunity discovery, rapid experiments, desirability, feasibility, and viability.', build: 'Prototype one new AI-enabled service or process improvement.', test: 'Run a small experiment with success, stop, and learning criteria.', manage: 'Limit scope, time, cost, and exposure before scaling.', present: 'Show what the experiment proved, disproved, and left unknown.', output: 'Innovation prototype + experiment card', studentQuestion: 'How do I test an AI idea without overinvesting?', studentWin: 'Run a bounded experiment and learn from evidence instead of enthusiasm.', career: 'Evaluate innovation opportunities before committing resources.', workload: '8–10 hours' },"
new_week12 = "  { week: 12, dates: 'Nov 9–15', title: 'AI and the Workforce', learn: 'Tasks versus jobs, automation, augmentation, human skills, worker voice, reskilling, and transition risk.', build: 'Add a Workforce Impact Map showing current tasks, AI opportunity, human-retained work, skills, training, risks, and management recommendations.', test: 'Check whether the plan distinguishes task change from job elimination and whether affected workers have realistic support and voice.', manage: 'Plan augmentation, reskilling, transition support, and safeguards for work that should remain human.', present: 'Defend which tasks AI may assist, which require human judgment, and what support workers need.', output: 'Workforce Impact Map + management recommendation', studentQuestion: 'How should a manager introduce AI without treating people as disposable?', studentWin: 'Plan AI-enabled work around tasks, human strengths, worker impact, and responsible transition.', career: 'Lead workforce change with clearer skill and transition planning.', workload: '8–10 hours' },"
replace_once(old_week12, new_week12, 'align Week 12 roadmap')

text = text.replace('AI and Plaigarism', 'AI and Plagiarism')

# 4) Carry forward safe Week 6/7 cleanup from the stale draft PR.
old_privacy = "Object.keys(structuredAnswers).filter((key) => key.startsWith('privacy-')).length >= 6"
new_privacy = "[0, 1, 2, 3, 4, 5].every((index) => Boolean(structuredAnswers[`privacy-${index}`]))"
replace_once(old_privacy, new_privacy, 'require all Week 6 privacy answers')

old_maturity = '''{structuredAnswers.maturityCurrent && <div className="decisionFeedback"><strong>Feedback</strong><p>Palmetto is closest to Level 1, Ad hoc. A reasonable next aim is Level 3, Managed: establish roles, policy, training, controls, and an incident route before claiming mature measurement.</p></div>}'''
new_maturity = '''{structuredAnswers.maturityCurrent && <div className="decisionFeedback"><strong>{structuredAnswers.maturityCurrent === '1 · Ad hoc' ? 'Correct diagnosis.' : 'Reconsider the current level.'}</strong><p>Given scattered use, no central owner, only a draft policy, and no monitoring or incident route, Palmetto is closest to Level 1 · Ad hoc. A reasonable next aim is Level 3 · Managed: establish roles, policy, training, controls, and an incident route before claiming mature measurement.</p></div>}'''
replace_once(old_maturity, new_maturity, 'make Week 7 maturity feedback conditional')

old_brightpath = '''<p>BrightPath wants to use AI to screen applicants. Start with the questions you need, then reveal one fact at a time.</p><div className="caseReveal"><strong>ROUND 1 · WHAT DO YOU NEED TO KNOW?</strong><textarea value={String(structuredAnswers.brightpathQuestions || '')} onChange={(event) => answerStructured('brightpathQuestions', event.target.value)} placeholder="Purpose, data, affected people, error patterns, oversight, accountability..." /></div>{Number(structuredAnswers.brightpathRound || 1) >= 2 && <div className="caseReveal"><strong>ROUND 2 · HISTORICAL DATA</strong><p>The model was trained partly on historical hiring decisions. This increases the need to examine representation, criteria, and unequal outcomes.</p></div>}{Number(structuredAnswers.brightpathRound || 1) >= 3 && <div className="caseReveal"><strong>ROUND 3 · 95% ACCURACY</strong><p>The vendor reports 95% accuracy, but does not provide error distribution, fairness measures, or the definition of accuracy.</p></div>}{Number(structuredAnswers.brightpathRound || 1) >= 4 && <div className="caseReveal"><strong>ROUND 4 · AUTOMATIC REJECTION</strong><p>Require human review, testing and monitoring, documentation, accountability, data restrictions, and an appropriate review or appeal path.</p></div>}<button className="primaryAction" type="button" onClick={() => answerStructured('brightpathRound', Math.min(4, Number(structuredAnswers.brightpathRound || 1) + 1))}>{Number(structuredAnswers.brightpathRound || 1) < 4 ? 'Reveal next round' : 'Case complete'}</button>'''
new_brightpath = '''<p>BrightPath wants to use AI to screen applicants. Start with the questions you need, then reveal one fact at a time and update your risk judgment.</p><div className="caseReveal"><strong>ROUND 1 · WHAT DO YOU NEED TO KNOW?</strong><textarea value={String(structuredAnswers.brightpathQuestions || '')} onChange={(event) => answerStructured('brightpathQuestions', event.target.value)} placeholder="Purpose, data, affected people, error patterns, oversight, accountability..." /></div>{Number(structuredAnswers.brightpathRound || 1) >= 2 && <div className="caseReveal"><strong>ROUND 2 · HISTORICAL DATA</strong><p>The model was trained partly on historical hiring decisions from a workforce that was not demographically representative. Reassess representation, job-relatedness, and possible unequal outcomes.</p></div>}{Number(structuredAnswers.brightpathRound || 1) >= 3 && <div className="caseReveal"><strong>ROUND 3 · VENDOR CLAIM</strong><p>The vendor reports 95% accuracy but does not provide the definition of accuracy, error distribution, fairness measures, or group-level results.</p></div>}{Number(structuredAnswers.brightpathRound || 1) >= 4 && <div className="caseReveal"><strong>ROUND 4 · AUTOMATIC REJECTION</strong><p>Applicants scoring below 60 are automatically rejected before a recruiter reviews them. The vendor also processes applicant personal information outside BrightPath.</p><fieldset><legend>Final management recommendation</legend>{['Approve', 'Approve with safeguards', 'Pause pending evidence', 'Do not use'].map((choice) => <label className="choiceLabel" key={choice}><input type="radio" name="brightpath-final" checked={structuredAnswers.brightpathDecision === choice} onChange={() => answerStructured('brightpathDecision', choice)} />{choice}</label>)}</fieldset><textarea value={String(structuredAnswers.brightpathRationale || '')} onChange={(event) => answerStructured('brightpathRationale', event.target.value)} placeholder="Explain the risk level, evidence, stakeholders, safeguards, accountable owner, human oversight, and what additional evidence you need." /></div>}<button className="primaryAction" type="button" disabled={Number(structuredAnswers.brightpathRound || 1) === 1 && !String(structuredAnswers.brightpathQuestions || '').trim()} onClick={() => answerStructured('brightpathRound', Math.min(4, Number(structuredAnswers.brightpathRound || 1) + 1))}>{Number(structuredAnswers.brightpathRound || 1) < 4 ? 'Reveal next round' : 'Case evidence fully revealed'}</button>'''
replace_once(old_brightpath, new_brightpath, 'strengthen BrightPath progression')

PAGE.write_text(text)
print('Course integration stabilization applied successfully.')
